### ISSUE TITLE
v0.23.0 Release Tracking Issue

### ISSUE THREAD

**Issue by ianlivingstone** [manifoldco/torus-cli#230]
**Status**: Active 
**Current RC CLI:** v0.23.0-rc.0

### Release Criteria

- [x] All builds passing
- [x] Change Log prepared
- [x] QA Checklist Complete
- [x] All bugs fixed or triaged
- [x] Deployed and Released
- [x] KB & WWW on latest version of the CLI

**Comment by ianlivingstone** [comment]
### Commits

```
Federico Ruggi (11):
      fetch updates in background and get them in user cli
      fixed download url
      return error if actual call fails
      added godoc lines
      added godoc, moved `apitypes.Updates` to `apitypes.UpdateInfo`
      removed unused tabwriter, added godoc for cmd.checkUpdates
      added documentation for `check_updates` preference
      use UTC timezone
      use semver for versions comparison, ignore race condition on readfile
      better update check logic, added tests
      added godoc, simplified error detection in `updates.getLastCheck`

Ian Livingstone (4):
      Fix machine name check
      Add security note regarding named pipes

James Bowes (38):
      organize worklog keyring items by user, not keyring
      Implement unmarshaling keyring membership revocation reasons
      Update changelog with updates checking support
      Install released versions of glide only
      Re-add keyring membership correction for machines
      Expose the claims causing the need for credential rotation
      Populate rich worklog details
      Make attributes and default icons public in promptui
      Allow prompts to have indent characters
      Different types for keyring membership
      New worklog UI
      Remove the worklog result type; its unused
      Fix the org flag help for invites accept
      Teach the ui package to spawn indented children
      Use ui.Child for indenting prefs output
      use ansiwrap
      Use the ui package for worklog output
      Check in our generated code, so we can go get it
      Fix padding addition for base32 when divisible by 8
      Use the external base64 dep
      Use our new external base32 package

Jeff Andersen (5):
      Use roundtripper instead of http.transport
      Extract validation methods for common types to be reused
      Remove dependency of config from logic engine
      Add database interface for logic engine to allow for use in additional client

Jelmer Snoeck (22):
      Config: encapsulate windows root path behaviour.
      Compile: easily compile to windows executable.
      Daemon: Windows specific daemon spawning.
      API/Daemon: Unix Socket/Windows TCP.
      Dirprefs: windows and unix have different roots.
      Styler: windows specific styler.
      Appveyor: add build file.
      Windows: set homedrive accordingly.
      Config: TransportAddress instead of SocketPath.
      Glide: add npipe.
      Windows: implement npipe.
      Appveyor
      Promptui: use readline.Stdout.
      Styles: fallback to latin characters on Windows.
      Makefile: set up to build binaries for Windows.
      README: add Windows install instructions.
      Readme: proper formatting for Windows installation.
      WindowsSocket: don't use backslash in address.
      WindowsSocket: add default security behaviour.
      Transport: use DialTimeout.
      HTTPClient: set up Timeout.
      Timeouts: bump client timeout to 1 minute.

Patrick LaRoche (1):
      Update release-issue.md
```

**Comment by ianlivingstone** [comment]
```
================================================================================================================================================================================================================================================================================
Release 0.23.0-rc.1 is ready for stage

zips: https://prerelease.torus.sh/0.23.0-rc.1/

npm:  npm install -g https://prerelease.torus.sh/npm/0.23.0-rc.1/torus.tar.gz
brew: brew install https://prerelease.torus.sh/brew/0.23.0-rc.1/torus.rb

yum:
sudo tee /etc/yum.repos.d/torus.repo <<-'EOF'
[torus]
name=torus-cli repository
baseurl=https://prerelease.torus.sh/rpm//
enabled=1
gpgcheck=0
EOF
sudo yum install torus # or dnf

deb:
DISTRO=$(lsb_release -i | awk '{print tolower($3)}')
CODENAME=$(lsb_release -c | awk ‘{print $2})’
sudo tee /etc/apt/sources.list.d/torus.list \
    <<< "deb https://prerelease.torus.sh/$DISTRO/ $CODENAME main"
sudo apt-get update
sudo apt-get install torus

================================================================================================================================================================================================================================================================================
```

**Comment by ianlivingstone** [comment]
### Installation and Signup

If you have `torus` installed, start fresh `npm uninstall -g torus-cli`

- [ ]   `npm install -g torus-cli` installs `torus`
- [ ]   `torus help` displays the help prompt after an
        `npm install -g torus-cli`
- [ ]   `torus prefs list` displays the path to your `public_key_file`
- [ ]   `torus signup` prompts you for an verification code username, name and
        email, before verifying and authenticating you
- [ ]   A user cannot perform any writes without verifying their account
- [ ]   `torus status` displays your current working context
- [ ]   `torus logout` logs you out
- [ ]   `torus login` prompts you for an email and password, before
        authenticating you
- [ ]   You can login using environment variables (`TORUS_EMAIL` and
        `TORUS_PASSWORD`)

### Account

- [ ]   `torus profile view` displays your current identity
- [ ]   `torus profile update` allows you to change your name, email and
        password.
- [ ]   Changing email generates a new verification code
- [ ]   A user cannot perform any writes without verifying their account

### Teams

- [ ]   `torus teams list --org [username]` displays `owner` `admin` and
        `member` teams, and you are a member of each
- [ ]   `torus teams create [name] --org [org-name]` creates an org.
- [ ]   `torus invites send [email] —org [org-name]` generates an access code
        and sends it to the user
- [ ]   `torus invites accept —org [org] [email] [code]` prompts a user to
        sign-up or login
- [ ]   The user cannot manage resources in this org
- [ ]   `torus invites list —org [org]` lists the outstanding invite
- [ ]   `torus invites approve [email] —org [org]` approves the users invite
- [ ]   The user is now a member of the members team
- [ ]   `torus teams add [name] [username] —org [org-name]` adds the user to a
        team
- [ ]   `torus teams remove [name] [username] —org [org-name]` removes the user
        from a team
- [ ]   Users cannot remove themselves from system-teams

### Context

- [ ]   `torus status` will not display a context outside of a linked directory
- [ ]   `torus link` prompts you to select or create an org, and project
- [ ]   `torus link -f` will over-write a previous `torus link`
- [ ]   `torus status` now displays a valid: org, project, environment, service,
        instance and path
- [ ]   Commands can now be executed without the `—org` and `--project` flags

### Access Controls

- [ ]   `torus policies list --org [org]` displays three `system-default`
        policies attched to the `owner` , `admin` , and `member` teams
- [ ]   `torus allow crudl [path] [team]` generates a policy, displays an
        `allow` effect, appropriate actions, the correct resource. and attaches
        it to `[team]`
- [ ]   Members of `[team]` have appropriate access
- [ ]   `torus deny crudl [path] [team]` generates a policy, with a `deny`
        effect, appropriate actions, the correct resource, and attaches it to
        `[team]`
- [ ]   Members of `[team]` are denied access to the appropriate resource
- [ ]   `torus policies list —org [org]` displays the generated policies
        attached to the appripriate `[team]`
- [ ]   `torus policies detach [name] [team] —org [org]` detaches the policy
        from the team
- [ ]   Members of `[team]` have appropriate access
- [ ]   System policies cannot be detached
- [ ]   `torus policies view [name]` displays statements contained within the
        policy

### Worklog/Keyring Versioning

- [ ]   *Keyring Versioning*
  - [ ]   *prerequisite:* Create an org, and invite another user.
  - [ ]   *prerequisite:* Create a team, add the other user to it, and give it
          access to a project (`projA`)
  - [ ]   *prerequisite:* Create a second project (`projB`) that the other user
          does not have access to.
  - [ ]   *prerequisite:* Set two secrets in both projects
  - [ ]   `torus orgs remove [username] —org [org-name]` removes the user from
          the org.
  - [ ]   `torus worklog list` shows the secrets from `projA` as needing to be
          changed, but does not show the secrets from `projB`.
  - [ ]   `torus worklog view <id>` shows a worklog entry by id.
  - [ ]   After each secret from `projA` is changed, it no longer appears in the
          worklog.
  - [ ]   `torus view` can display a mixture of old and new secrets (ie after a
          single new set in `projA`).
- [ ]   *Keypair revocation*
  - [ ]   *prerequisite:* Create an org, and invite another user.
  - [ ]   *prerequisite:* Create a team, add the other user to it, and give it
          access to a project (`projA`)
  - [ ]   *prerequisite:* Set a secret in the project
  - [ ]   Run `torus keypairs revoke` as the other user, to revoke your keypairs
  - [ ]   The other user now cannot see any secrets with `torus view`
  - [ ]   As the first user, `torus worklog list` should show a secrets item
          to rotate the secret.
  - [ ]   Run `torus set` as the first user, to set a *new* secret. It should
          not error (the revoked keypairs should cause no issues).
  - [ ]   Run `torus keypairs generate` as the other user.
  - [ ]   The first user should now see keyring entries in the worklog, to
          encode the other user's new keypairs.
  - [ ]   `torus worklog resolve` should resolve the keyring entries.
  - [ ]   The other user should be able to `torus view` the original secret,
          and the new secret.

### List

- [ ]   `torus ls`, in an unlinked directory, list all orgs
- [ ]   `torus ls` works in a linked directory, showing all paths for the
        context
- [ ]   `torus ls /` lists all orgs
- [ ]   `torus ls "/*"` lists all projects
- [ ]   `torus ls "/*/*"` lists all environments
- [ ]   `torus ls "/*/*/*"` lists all services
- [ ]   `torus ls "/$org/$proj/*/*"` lists all secrets for `/$org/$proj/*/*/*`

### Machines

- [ ]   Only admins and owners can create machines
- [ ]   `torus machines create` works with context
- [ ]   `torus machines create` supports flags (e.g. `-o, -t` etc)
- [ ]   `torus machines create` allows you to select an existing org and team
- [ ]   `torus machines create` allows you to create a new machine team
- [ ]   You can login using `TORUS_TOKEN_ID` and `TORUS_TOKEN_SECRET`
        environment variables
- [ ]   A machine can read but not write (e.g. `view, run, ls, envs list,
        services list, projects list, orgs list, status`)
- [ ]   `torus machines list` displays all machines
- [ ]   `torus machines list --role [role]` shows machines belonging to that
        team
- [ ]   `torus machines list --destroyed` shows destroyed machines
- [ ]   `torus machines view [identity]` shows a single machine's details by id
- [ ]   `torus machines view [name]` shows a single machine's details by name
- [ ]   `torus machines destroy [identity]` destroys a machine by id after
        confirming
- [ ]   `torus machines destroy [name]` destroys a machine by name after
        confirming
- [ ]   `torus machines list --destroyed` shows only destroyed machines
- [ ]   `torus machines roles create` creates a machine role
- [ ]   `torus machines roles lists` lists all machine roles (including the
        machine team)

### Critical Path

- [ ]   `torus orgs create [name]` creates an org.
- [ ]   `torus projects create [name] —org [org]` creates a project.
- [ ]   `torus services create [name] —project [project] —org [org]` creates a
        service.
- [ ]   `torus set [key] [value] —service [service]` will set the variable
- [ ]   You can set using environment variables (e.g. `TORUS_ORG`)
- [ ]   You can not set variables in services that do not exist
- [ ]   `torus set [path] [value]` will set the variable
- [ ]   `torus view —service [service]` will list secrets
- [ ]   A secret can be set across services
- [ ]   A secret can be set across environments
- [ ]   More specific paths win
- [ ]   Latest set wins
- [ ]   `torus run <command> —service [service]` will inject secrets and execute
        the command
- [ ]   `torus run <command>` without a service defaults to "default" service
- [ ]   `torus unset [key] —service [service]` will unset the variable
