### ISSUE TITLE
Secret Retrieval Performance

### ISSUE THREAD

**Issue by ianlivingstone** [manifoldco/torus-cli#302]
We've had a few people reach out to ask about performance improvements related to speeding up `torus run` and credential retrieval in general. As the number of unset and set credentials increases inside a path retrieval slows down.

I took a quick stab last night looking at what could be done today to improve retrieval. I've put a short list together below, but none of this is backed by any data based on benchmarking!

- [x] ~Skip unboxing of unset credentials, we only need to unbox always unbox v1 credentials as the fact they're unset is stored inside the CredentialValue instead of on the `state` field (which was added in v2 of the object).~ (Already done inside the daemon)
- [x] Pull sorting through unset and set credentials into the Daemon. Right now it lives inside the CLI which means we decrypt every single credential object inside a keyring and send the contents to the CLI or any other client. We can speed this up by moving the responsibility for sorting through set/unset into the Daemon and never sending unset to the CLI. In future we could add a query parameter to the retrieval route for including unset credentials if they're needed for a future command.
- [x] Break the unboxer into two parts, one which unboxes a Private Key, and another for actually unboxing a Keyring. This way we can group decryption by public key. The implication here is that most keyring memberships leverage the same public key for a user, so this should drastically reduce the number of private keys we need to unbox using the stored master key.
- [ ] ~Using go channels to parallelize decrypting different keyrings~ 
- [x] Parallelize retrieving the credentialgraph, claimtree and keypairs for a user

A few next steps:

- Get a profiler in place so it's easier to find the specific slowdowns/slow spots to determine where we're spending the most time.
- Get a few standard data sets in place to make it easy to benchmark as changes are made
